# ROI Detection Pipeline Configuration
# This file contains all the configuration parameters for the automated pipeline

# Experiment Configuration
experiment:
  name: "pcla_3class"
  description: "Automated ROI Detection Pipeline"
  version: "1.0"

# Data Paths
data:
  # Input data directories
  data_dir: "PATH_TO_SAVE_MEL/PATCHES"  # Directory containing .h5 files
  csv_path: "PATH_TO_CSV"  # CSV file with slide_id, data_split, label_name
  wsi_dir: "PATH_TO_WSI"  # Directory containing .svs files
  
  # Annotation directories
  xml_annotation_new: "PATH_TO_SAVE_ANNOTATED_PATCHES/ANNOTATIONS_NEW"
  xml_annotation_other: "PATH_TO_SAVE_ANNOTATED_PATCHES/ANNOTATIONS_OTHER"
  xml_dir: "PATH_TO_GROUND_TRUTH_LABELS"  # For visualization
  
  # Output directories
  feat_dir: "PATH_TO_SAVE_FEATURES"  # Extracted patches
  results_dir: "PATH_TO_SAVE_RESULTS"  # All results
  models_save_folder: "./saved_models/"  # Trained models
  classification_save_dir: "PATH_TO_SAVE_CLASSIFICATION_RESULTS"

# Model Configuration
model:
  architecture: "vgg16"
  num_classes: 3
  batch_size: 100
  n_epochs: 20
  learning_rate: 5e-4
  weight_decay: 1e-4
  patience: 20  # Early stopping patience
  start_epoch: 0

# Patch Configuration
patches:
  patch_size: 256
  target_patch_size: -1  # -1 means no scaling
  annotation_ratio: 0.5  # Ratio for in-region detection

# Visualization Configuration
visualization:
  percent: 0.2  # Top percentage for visualization
  generate_heatmap: true
  generate_boundary: true
  generate_overlay: true
  auto_skip: true  # Skip existing files

# Normalization Parameters (from method_pcla_3class.py)
normalization:
  mean: [0.6632, 0.4123, 0.5529]
  std: [0.1618, 0.1749, 0.1478]

# Pipeline Control
pipeline:
  # Which steps to run
  extract_patches: true
  train_model: true
  score_patches: true
  generate_visualizations: true
  run_analysis: true
  
  # Skip steps if outputs exist
  skip_existing: true
  
  # Clean up intermediate files
  cleanup_intermediate: false

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "pipeline.log"
  log_to_console: true

# Hardware Configuration
hardware:
  use_gpu: true
  num_workers: 4  # For data loading
  pin_memory: true
